# Generated by Django 5.2.10 on 2026-06-23

from django.db import migrations


def seed_prioridades_etiquetas(apps, schema_editor):
    Prioridad = apps.get_model('tareas_app', 'Prioridad')
    Etiqueta = apps.get_model('tareas_app', 'Etiqueta')

    prioridades = [
        {'nombre': 'Muy baja', 'orden': 10},
        {'nombre': 'Baja', 'orden': 20},
        {'nombre': 'Media', 'orden': 30},
        {'nombre': 'Alta', 'orden': 40},
        {'nombre': 'Muy alta', 'orden': 50},
        {'nombre': 'Urgente', 'orden': 60},
    ]

    for p in prioridades:
        Prioridad.objects.update_or_create(nombre=p['nombre'], defaults={'orden': p['orden']})

    etiquetas = [
        'Trabajo',
        'Personal',
        'Escuela',
        'Salud',
        'Finanzas',
        'Compras',
        'Viajes',
        'Importante',
        'Seguimiento',
        'Proyectos',
    ]

    # En el modelo, slug se autogenera en save() si viene vacío.
    # Pero en migrations no se ejecuta ese save() con datos incompletos como esperamos,
    # además slug tiene UNIQUE y blank=True.
    # Por eso generamos el slug explícitamente para evitar violaciones.
    import re

    def _slugify_es(s: str) -> str:
        s = s.strip().lower()
        # reemplazos básicos de acentos
        replacements = {
            'á': 'a', 'é': 'e', 'í': 'i', 'ó': 'o', 'ú': 'u', 'ñ': 'n',
            'ä': 'a', 'ë': 'e', 'ï': 'i', 'ö': 'o', 'ü': 'u',
        }
        for k, v in replacements.items():
            s = s.replace(k, v)
        s = re.sub(r'[^a-z0-9]+', '-', s)
        s = re.sub(r'-{2,}', '-', s)
        return s.strip('-')

    for nombre in etiquetas:
        slug = _slugify_es(nombre)
        Etiqueta.objects.update_or_create(
            slug=slug,
            defaults={'nombre': nombre},
        )



class Migration(migrations.Migration):
    dependencies = [
        ('tareas_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_prioridades_etiquetas, migrations.RunPython.noop),
    ]

